name: mri_v1
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - nibabel
  - pip:
      - monai
      - torch
      - torchvision
      - torchaudio